const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { once } = require("node:events");
const { createFleetStore } = require("../fleet");

const team = "DEMO1234";
const task = (overrides = {}) => ({ id: "clickup:newsletter:abc", title: "Newsletter", workflow: "newsletter", status: "blocked", phase: "Freigabe fehlt", workerId: "mac-1", updatedAt: "2026-10-08T08:00:00Z", ...overrides });
const queue = (tasks) => ({ tasks, source: { name: "ClickUp" } });

test("manual completion persists, broadcasts once and expires with a new blocking state", (t) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "max-monitor-completions-"));
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }));
  const store = createFleetStore(directory);
  store.updateQueue(team, queue([task(), task({ id: "failed", status: "failed" }), task({ id: "running", status: "running" })]));
  const version = store.snapshot(team).queue.tasks[0].taskVersion;
  const request = { taskId: task().id, taskVersion: version };
  let signals = 0;
  store.subscribe(team, () => signals++);
  const completed = store.completeTask(team, { member: { id: "viewer" } }, request);
  assert.equal(completed.status, "completed");
  assert.equal(completed.completion, "manual");
  assert.equal(completed.phase, "Manuell erledigt");
  assert.ok(completed.completedAt);
  assert.equal(signals, 1);
  assert.deepEqual(store.completeTask(team, {}, request), completed);
  assert.equal(signals, 1);
  const event = store.snapshot(team).events.find((event) => event.type === "task_completed");
  assert.equal(event.workerId, "mac-1");
  assert.equal(event.workflow, "newsletter");
  const saved = JSON.parse(fs.readFileSync(path.join(directory, team, "fleet.json"), "utf8"));
  assert.equal(saved.queue.tasks[0].status, "blocked");
  assert.equal(saved.queue.completions[0].completedBy, "viewer");
  assert.equal(createFleetStore(directory).snapshot(team).queue.tasks[0].completion, "manual");

  store.updateQueue(team, { source: { name: "ClickUp", error: "Unavailable" } });
  assert.equal(store.snapshot(team).queue.tasks[0].completion, "manual");
  store.updateQueue(team, queue([task({ title: "Umbenannt", updatedAt: new Date().toISOString() })]));
  assert.equal(store.snapshot(team).queue.tasks[0].completion, "manual");
  store.updateQueue(team, queue([task({ phase: "Neue Blockierung" })]));
  assert.equal(store.snapshot(team).queue.tasks[0].status, "blocked");
  assert.throws(() => store.completeTask(team, {}, request), (error) => error.status === 409);
  const next = store.snapshot(team).queue.tasks[0];
  store.completeTask(team, {}, { taskId: next.id, taskVersion: next.taskVersion });
  store.updateQueue(team, queue([task({ phase: "Neue Blockierung", status: "running" })]));
  assert.equal(store.snapshot(team).queue.tasks[0].status, "running");
  store.updateQueue(team, queue([task({ phase: "Neue Blockierung" })]));
  assert.equal(store.snapshot(team).queue.tasks[0].status, "blocked");
  const retry = store.snapshot(team).queue.tasks[0];
  store.completeTask(team, {}, { taskId: retry.id, taskVersion: retry.taskVersion });
  store.updateQueue(team, queue([]));
  assert.throws(() => store.completeTask(team, {}, request), (error) => error.status === 404);
  store.updateQueue(team, queue([task()]));
  assert.equal(store.snapshot(team).queue.tasks[0].status, "blocked");
});

test("HTTP completion is shared by members, validates state and survives a server restart", async (t) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "max-monitor-completion-http-"));
  process.env.DATA_DIR = directory;
  process.env.TEAM_TOKEN = "completion-owner";
  delete process.env.TEAM_TOKENS;
  const { server } = require("../server");
  const start = async () => { server.listen(0, "127.0.0.1"); await once(server, "listening"); return `http://127.0.0.1:${server.address().port}`; };
  const stop = async () => { await new Promise((resolve) => server.close(resolve)); };
  let base = await start();
  t.after(async () => { await stop(); fs.rmSync(directory, { recursive: true, force: true }); });
  const request = async (route, method = "GET", body, token = "completion-owner") => {
    const res = await fetch(`${base}/v1/teams/${team}${route}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
    return { status: res.status, body: await res.json() };
  };
  const member = (await request("/members", "POST", { name: "Viewer" })).body.member;
  await request("/queue", "POST", queue([task(), task({ id: "running", status: "running" }), task({ id: "failed", status: "failed" })]));
  const entries = (await request("/fleet")).body.queue.tasks;
  const body = { taskId: entries[0].id, taskVersion: entries[0].taskVersion };
  assert.equal((await request("/fleet/tasks/complete", "POST", body, null)).status, 401);
  assert.equal((await request("/fleet/tasks/complete", "POST", body, "wrong")).status, 401);
  assert.equal((await request("/fleet/tasks/complete", "POST", { taskId: "missing", taskVersion: body.taskVersion }, member.token)).status, 404);
  assert.equal((await request("/fleet/tasks/complete", "POST", { ...body, taskVersion: "stale" }, member.token)).status, 409);
  assert.equal((await request("/fleet/tasks/complete", "POST", { taskId: "running", taskVersion: entries[1].taskVersion }, member.token)).status, 409);
  assert.equal((await request("/fleet/tasks/complete", "POST", {}, member.token)).status, 400);
  assert.equal((await request("/fleet/tasks/complete", "POST", null, member.token)).status, 400);
  const results = await Promise.all([request("/fleet/tasks/complete", "POST", body, member.token), request("/fleet/tasks/complete", "POST", body, member.token)]);
  assert.ok(results.every((res) => res.status === 200 && res.body.task.completion === "manual"));
  assert.equal((await request("/fleet/tasks/complete", "POST", { taskId: "failed", taskVersion: entries[2].taskVersion }, member.token)).status, 200);
  const shared = (await request("/fleet")).body;
  assert.equal(shared.queue.tasks[0].status, "completed");
  assert.equal(shared.events.filter((event) => event.type === "task_completed" && event.taskId === body.taskId).length, 1);
  assert.equal((await request("/queue", "POST", queue([]), member.token)).status, 403);
  await stop(); base = await start();
  assert.equal((await request("/fleet", "GET", undefined, member.token)).body.queue.tasks[0].completion, "manual");
});
